### ISSUE TITLE
Qnap 3k3y

### ISSUE THREAD

**Issue by SilentPTs** [xakep666/ps3netsrv-go#16]
I have a qnap ts-233 I used the built version of this but can't seem to get it to work after some testing I think the issue is with the 3k3y encryption, I could be wrong but I tried everything I could figure the image it's not mine I just searched similar issues people are having
![Screenshot_2024-02-14-23-40-47-37_3d419158bad5872c40592a6c9956e692-1](https://github.com/user-attachments/assets/6f1bb63c-6eac-44fd-b3ac-a964693dc882)

**Comment by xakep666** [comment]
Probably found a root cause of this problem. I'll attach a newly built binary so you can try it before release.

**Comment by SilentPTs** [comment]
Does that have the arm64 package ? I'm a little tech disabled I'm having someone building it and it didn't show up in processes he told me to ask

**Comment by xakep666** [comment]
@SilentPTs you have to unzip attached archive, copy executable to nas and replace old executable with new

**Comment by SilentPTs** [comment]
I appreciate the help, will try and test it out 😁

**Comment by SilentPTs** [comment]
It's working as intended now, thank you for everything😁
